# one dimensinal

import numpy as np
a=np.array([10,20,30])
print(type(a))
print(a.shape)

In [1]:
import numpy as np
a=np.array([10,20,30]) 
print(type(a)) 
print(a.shape)

<class 'numpy.ndarray'>
(3,)


In [2]:
print(a)

[10 20 30]


In [3]:
print(a[0])

10


In [4]:
a[0]=50

In [13]:
a

array([50, 20, 30])

# two dimensional

In [6]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
print(b.shape)

(2, 3)


In [8]:
print(b[1,2],b[0,1])


6 2


In [9]:
b[0,2]

3

# three diamensional

In [10]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
print(c.shape)

(3, 3)


In [12]:
c[1,2]

6

# numpy also provides many functions to create arrays

In [14]:
a=np.zeros((2,2))
print(a)
a.shape

[[0. 0.]
 [0. 0.]]


(2, 2)

In [62]:
b=np.ones((3,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
c=np.full((3,3),2)
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [17]:
d=np.eye(6)
print(d)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [5]:
e=np.random.random((3,2))
print(e)

[[0.96447578 0.84197084]
 [0.9685517  0.57385569]
 [0.05798674 0.74304681]]


In [8]:
f=np.arange(0,21,3)
f

array([ 0,  3,  6,  9, 12, 15, 18])

In [25]:
g=np.linspace(0,5,10)
g

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
import numpy as np
arr=np.array([[1,2,3,4],
            [5,2,4,2],
            [1,2,0,1]])
newarr=arr.reshape(2,2,3)
print("\n origional array:\n",arr)
print("\n reshape array:\n",newarr)


 origional array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 reshape array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]


In [22]:
a=np.array([[1,2,3],[4,5,6]])
flarr=a.flatten()
print("\n origional array:\n",a)
print("\n fattened array:\n",flarr)


 origional array:
 [[1 2 3]
 [4 5 6]]

 fattened array:
 [1 2 3 4 5 6]


# slicing array

In [30]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
b=a[0:2,1:3]
b

array([[2, 3],
       [6, 7]])

In [48]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [49]:
print(a[1,1])

6


In [50]:
a[0,1]=77
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
row_r1=a[2,:]
row_r2=a[1,:]
print(row_r1,row_r1.shape)
print(row_r2,row_r2.shape)

[ 9 10 11 12] (4,)
[5 6 7 8] (4,)


In [53]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
a[0,]

array([1, 2, 3, 4])

In [55]:
col_r1=a[:,1]
col_r1

array([ 2,  6, 10])

In [56]:
col_r2=a[:,2:]
col_r2

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [57]:
print(col_r1,col_r1.shape)
print(col_r2,col_r2.shape)

[ 2  6 10] (3,)
[[ 3  4]
 [ 7  8]
 [11 12]] (3, 2)


# integer array indexing:
when you index into numpy arrays

In [40]:
a=np.array([[-1,2,0,4],
            [4,-0.5,6,0],
            [2.6,0,7,8],
            [3,-7,4,2.0]])
a

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [41]:
temp=a[[0,1,2,3],[3,2,1,0]]
print("\n elements at indices(0,3),(1,2),(2,1),"
      "(3,0):\n",temp)


 elements at indices(0,3),(1,2),(2,1),(3,0):
 [4. 6. 0. 3.]


# boolean array

In [42]:
a

array([[-1. ,  2. ,  0. ,  4. ],
       [ 4. , -0.5,  6. ,  0. ],
       [ 2.6,  0. ,  7. ,  8. ],
       [ 3. , -7. ,  4. ,  2. ]])

In [43]:
cond=a>0
cond

array([[False,  True, False,  True],
       [ True, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True]])

In [44]:
cond=a%2==0
temp=a[cond]
print("\n elements greater than 0:\n",temp)


 elements greater than 0:
 [2. 0. 4. 4. 6. 0. 0. 8. 4. 2.]


# operations

In [46]:
a=np.array([1,2,5,3])
print("original elements",a)

print("adding 1 to every element:",a+1)

print("subtracting 3 from each element:",a-3 )
print("multiplying  each element by 10:",a*10 )
print("squaring  each element:",a**2 )
a*=2
print("doubled each element of origional array:",a)
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

print("\n origional array:\n",a)
print("\n ttanspose array:\n",a.T)

original elements [1 2 5 3]
adding 1 to every element: [2 3 6 4]
subtracting 3 from each element: [-2 -1  2  0]
multiplying  each element by 10: [10 20 50 30]
squaring  each element: [ 1  4 25  9]
doubled each element of origional array: [ 2  4 10  6]

 origional array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 ttanspose array:
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [58]:
arr=np.array([[1,5,6],
              [4,7,2],
              [3,1,9]])

print("largest element is:",arr.max())
print("row wise maximum element is:",arr.max(axis=1))

print("col wise maximum element is:",arr.max(axis=0))
print("sum of all array elements:",arr.sum())
print("cumulative sum along each row:\n",arr.cumsum(axis=1))

largest element is: 9
row wise maximum element is: [6 7 9]
col wise maximum element is: [4 7 9]
sum of all array elements: 38
cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]


In [66]:
a=np.array([[1,2],
            [3,4]])
b=np.array([[4,3],[2,1]])

print("Array sum:\n",a+b)

print("array multiplication:\n",a*b)

print("matrix multiplication:\n",a.dot(b))

Array sum:
 [[5 5]
 [5 5]]
array multiplication:
 [[4 6]
 [6 4]]
matrix multiplication:
 [[ 8  5]
 [20 13]]


In [67]:
a=np.array([25,16,4,9])
print("exponent of array elements:",np.log(a))

print("square root of array elements:",np.sqrt(a))

exponent of array elements: [3.21887582 2.77258872 1.38629436 2.19722458]
square root of array elements: [5. 4. 2. 3.]


# 

In [5]:
a=np.array([[1,4,2],
            [3,4,6],
            [0,-1,5]])

print("array element in sorted order:\n",np.sort(a,axis=None))

array element in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [69]:
print("col wise sorted array:\n",np.sort(a,axis=0))

col wise sorted array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]


In [70]:
print("row wise sort by applying merge-sort:\n",np.sort(a,axis=1))

row wise sort by applying merge-sort:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]
