### Q1

In [8]:
for i in range(2,101):
    if i>1:
        for j in range(2,i):
            if i%j==0:
                break
        else:   
            print(i,end=" ")

2 3 5 7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89 97 

### Q2

In [1]:
def reverse(str1):
    str1=str1[::-1]
    return str1
str1="vidya"
reverse(str1)

'aydiv'

### Q3

In [3]:
Days = ['Monday', 'tuesday','friday', 'Sunday', 'Saturday']
for i in Days:
    if i==i.title():
        print(i,end=" ")

Monday Sunday Saturday 

### Q4

In [28]:
Batch = ['15-06-1997','15-06-2011','15-06-1993','15-06-2020']
a=[x.split("-")[2] for x in Batch]
print(a)
    


['1997', '2011', '1993', '2020']


### Q5

In [26]:
Module = {'Data Science':1,'Machine Learning':2, 'SQL':3, 'BigData':4}
a={}
for i in Module.items():
    a[i[1]]=i[0]
print(a)
          

{1: 'Data Science', 2: 'Machine Learning', 3: 'SQL', 4: 'BigData'}


### Q6

In [ ]:

Input list: [5,2,1,4,6]
    

### Q7

In [97]:
a="vidya"
b=input()
count=0
whitespace=0
for w in b:
    if w==" ":
        whitespace=whitespace+1
for i in a:
    for j in b:
        if i==j:
            count=count+1
        
    c=len(b)-count
print(c-whitespace)


ab c d
2


### Q8

In [10]:
def checkrange(num):
    if (num>1000)& (num<10000):
        print("num is between 1000 and 10000")
    else:
        print("num is not between 1000 and 10000")
checkrange(1100)

num is between 1000 and 10000


### Q9

In [53]:
n = 6
for i in range(1, n+1):
    for j in range(0, n-i+1):
        print(' ', end='')
    C = 1
    for j in range(1, i+1):
        print(' ', C, sep='', end='')
        C = C * (i - j) // j
    print()

       1
      1 1
     1 2 1
    1 3 3 1
   1 4 6 4 1
  1 5 10 10 5 1


### Q10

In [12]:
test_score = [10, 32, 23, 14, 25]
sum=0
for i in test_score:
    sum=sum+i
print("sum of list ele is:",sum)
    

sum of list ele is: 104


### Q11

In [14]:
import numpy as np
Score = np.array([[210, 402, 383],
[140, 375, 106],
[140, 125, 217],
[292, 240, 295]])
Score

array([[210, 402, 383],
       [140, 375, 106],
       [140, 125, 217],
       [292, 240, 295]])

In [15]:
Score.min(axis=1)

array([210, 106, 125, 240])

### Q12

In [16]:
num_array = np.array([0, 21, 32, 13, 44, 45,
26, 28, 38, 34, 65, 48, 76])
num_array

array([ 0, 21, 32, 13, 44, 45, 26, 28, 38, 34, 65, 48, 76])

In [19]:
for i in num_array:
    if i%2==0:
        i=-1
    print(i,end=" ")

-1 21 -1 13 -1 45 -1 -1 -1 -1 65 -1 -1 